service: milio

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}